//! Users & privileges commands (#732): list MySQL accounts / PostgreSQL
//! roles and their privilege matrix, and apply GRANT/REVOKE/CREATE USER/
//! DROP USER/ALTER PASSWORD SQL generated by `db::privileges`.
//!
//! Follows the same "generate, preview, apply" separation as Diff/Sync
//! (`commands::sync`): SQL generation is pure and side-effect free, the
//! frontend previews it, and [`apply_privilege_sql`] only runs after
//! explicit user confirmation. The apply path deliberately mirrors
//! [`crate::commands::sync::apply_sync_sql_inner`] rather than
//! `run_query_transaction` — it calls `execute_transaction` directly and
//! never calls `record_history`/logs the statement text, so a password
//! embedded in a `CREATE USER`/`ALTER USER`/`CREATE ROLE`/`ALTER ROLE`
//! statement is never written to the query-history database or the log file
//! (see CLAUDE.md's secret-separation policy).

use tauri::State;

use crate::db::privileges::{
    generate_alter_password_sql as generate_alter_password,
    generate_create_user_sql as generate_create_user, generate_drop_user_sql as generate_drop_user,
    generate_grant_sql as generate_grant, generate_revoke_sql as generate_revoke, GrantSpec,
    UserSpec,
};
use crate::db::types::{DbUserInfo, UserPrivileges};
use crate::db::DriverKind;
use crate::error::{AppError, Result};
use crate::state::AppState;

/// Lists server accounts (MySQL) / roles (PostgreSQL) for the users panel.
/// Read-only, so allowed on read-only sessions (same policy as
/// `list_processes`). SQLite sessions get the driver's "unsupported" error.
#[tauri::command]
pub async fn list_db_users(
    session_id: String,
    state: State<'_, AppState>,
) -> Result<Vec<DbUserInfo>> {
    let session = state
        .get(&session_id)
        .await
        .ok_or_else(|| AppError::SessionNotFound(session_id.clone()))?;
    session.conn.list_db_users().await
}

/// The CRUD + DDL privilege matrix for one user/role. Read-only.
#[tauri::command]
pub async fn list_user_privileges(
    session_id: String,
    user: String,
    host: Option<String>,
    state: State<'_, AppState>,
) -> Result<UserPrivileges> {
    let session = state
        .get(&session_id)
        .await
        .ok_or_else(|| AppError::SessionNotFound(session_id.clone()))?;
    session.conn.user_privileges(&user, host.as_deref()).await
}

/// Renders `CREATE USER`/`CREATE ROLE`. Pure — no round trip, no logging (the
/// spec may carry a plaintext password).
#[tauri::command]
pub fn generate_create_user_sql(driver: DriverKind, spec: UserSpec) -> String {
    generate_create_user(driver, &spec)
}

/// Renders `DROP USER`/`DROP ROLE`. Pure.
#[tauri::command]
pub fn generate_drop_user_sql(driver: DriverKind, name: String, host: Option<String>) -> String {
    generate_drop_user(driver, &name, host.as_deref())
}

/// Renders `ALTER USER ... IDENTIFIED BY` / `ALTER ROLE ... PASSWORD`. Pure —
/// no logging (the password is embedded in the returned SQL text).
#[tauri::command]
pub fn generate_alter_password_sql(
    driver: DriverKind,
    name: String,
    host: Option<String>,
    password: String,
) -> String {
    generate_alter_password(driver, &name, host.as_deref(), &password)
}

/// Renders `GRANT <privs> ON ... TO ...`. `null` to the frontend when no
/// privilege flags are set (nothing to grant). Pure.
#[tauri::command]
pub fn generate_grant_sql(driver: DriverKind, spec: GrantSpec) -> Option<String> {
    generate_grant(driver, &spec)
}

/// Renders `REVOKE <privs> ON ... FROM ...`. Pure.
#[tauri::command]
pub fn generate_revoke_sql(driver: DriverKind, spec: GrantSpec) -> Option<String> {
    generate_revoke(driver, &spec)
}

/// Applies previously generated/confirmed statements (`CREATE USER` /
/// `DROP USER` / `ALTER ... PASSWORD` / `GRANT` / `REVOKE`) on `session_id`
/// inside one transaction. Mirrors
/// [`crate::commands::sync::apply_sync_sql_inner`]: rejects read-only
/// sessions outright, and — unlike `run_query_transaction` — never records
/// the (possibly password-bearing) SQL text to query history or logs.
#[tauri::command]
pub async fn apply_privilege_sql(
    session_id: String,
    database: Option<String>,
    statements: Vec<String>,
    state: State<'_, AppState>,
) -> Result<u64> {
    apply_privilege_sql_inner(state.inner(), session_id, database, statements).await
}

/// Core of [`apply_privilege_sql`] decoupled from Tauri's `State` wrapper so
/// integration tests can drive the exact command path (session lookup +
/// read-only guard + empty-statement guard + transactional apply) without
/// standing up a Tauri runtime.
pub(crate) async fn apply_privilege_sql_inner(
    state: &AppState,
    session_id: String,
    database: Option<String>,
    statements: Vec<String>,
) -> Result<u64> {
    let session = state
        .get(&session_id)
        .await
        .ok_or_else(|| AppError::SessionNotFound(session_id.clone()))?;

    if session.read_only {
        return Err(AppError::ReadOnly(
            "read-only session: user/privilege changes cannot be applied".into(),
        ));
    }
    if statements.is_empty() {
        return Err(AppError::InvalidInput(
            "no statements selected to apply".into(),
        ));
    }

    session
        .conn
        .execute_transaction(&statements, database.as_deref())
        .await
}
