import { describe, expect, it } from "vitest";
import { buildCreateTableSql, formatDefault, type ColumnDef } from "../components/createTable";

const col = (over: Partial<ColumnDef>): ColumnDef => ({
  name: "c",
  type: "TEXT",
  notNull: false,
  primaryKey: false,
  unique: false,
  autoIncrement: false,
  defaultValue: "",
  ...over,
});

describe("formatDefault", () => {
  it("returns null for empty", () => {
    expect(formatDefault("mysql", "  ")).toBeNull();
  });
  it("passes through numbers and known keywords", () => {
    expect(formatDefault("mysql", "42")).toBe("42");
    expect(formatDefault("mysql", "-1.5")).toBe("-1.5");
    expect(formatDefault("postgres", "current_timestamp")).toBe("CURRENT_TIMESTAMP");
    expect(formatDefault("sqlite", "null")).toBe("NULL");
  });
  it("quotes other values as string literals", () => {
    expect(formatDefault("mysql", "hello")).toBe("'hello'");
    expect(formatDefault("postgres", "O'Brien")).toBe("'O''Brien'");
  });
});

describe("buildCreateTableSql", () => {
  it("builds a MySQL table with auto-increment PK and backtick idents", () => {
    const sql = buildCreateTableSql("mysql", {
      database: "shop",
      table: "users",
      columns: [
        col({ name: "id", type: "INT", primaryKey: true, autoIncrement: true, notNull: true }),
        col({ name: "email", type: "VARCHAR(255)", notNull: true, unique: true }),
      ],
    });
    expect(sql).toContain("CREATE TABLE `shop`.`users`");
    expect(sql).toContain("`id` INT NOT NULL AUTO_INCREMENT");
    expect(sql).toContain("`email` VARCHAR(255) NOT NULL UNIQUE");
    expect(sql).toContain("PRIMARY KEY (`id`)");
  });

  it("uses double-quote idents and IDENTITY for PostgreSQL", () => {
    const sql = buildCreateTableSql("postgres", {
      database: "public",
      table: "t",
      columns: [col({ name: "id", type: "BIGINT", primaryKey: true, autoIncrement: true })],
    });
    expect(sql).toContain('CREATE TABLE "public"."t"');
    expect(sql).toContain('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY');
    expect(sql).toContain('PRIMARY KEY ("id")');
  });

  it("emits SQLite INTEGER PRIMARY KEY AUTOINCREMENT inline (no table-level PK)", () => {
    const sql = buildCreateTableSql("sqlite", {
      table: "t",
      columns: [
        col({ name: "id", type: "INTEGER", primaryKey: true, autoIncrement: true }),
        col({ name: "label", type: "TEXT", notNull: true }),
      ],
    });
    expect(sql).toContain('CREATE TABLE "t"');
    expect(sql).toContain('"id" INTEGER PRIMARY KEY AUTOINCREMENT');
    expect(sql).not.toContain("PRIMARY KEY (");
    expect(sql).toContain('"label" TEXT NOT NULL');
  });

  it("supports a composite primary key", () => {
    const sql = buildCreateTableSql("mysql", {
      table: "t",
      columns: [
        col({ name: "a", type: "INT", primaryKey: true }),
        col({ name: "b", type: "INT", primaryKey: true }),
      ],
    });
    expect(sql).toContain("PRIMARY KEY (`a`, `b`)");
  });

  it("escapes a string DEFAULT", () => {
    const sql = buildCreateTableSql("mysql", {
      table: "t",
      columns: [col({ name: "status", type: "VARCHAR(20)", defaultValue: "active" })],
    });
    expect(sql).toContain("`status` VARCHAR(20) DEFAULT 'active'");
  });

  it("omits the database qualifier for SQLite", () => {
    const sql = buildCreateTableSql("sqlite", {
      database: "ignored",
      table: "t",
      columns: [col({ name: "x", type: "TEXT" })],
    });
    expect(sql).toContain('CREATE TABLE "t"');
    expect(sql).not.toContain("ignored");
  });
});
