import { describe, expect, it, vi } from "vitest";
import {
  BUNDLE_CSP,
  buildInvestigationBundleHtml,
  bundlePlanSupported,
  bundleSchemaTargets,
  escapeHtml,
  extractReferencedTables,
  highlightSqlHtml,
  loadBundleSchema,
  tokenizeSql,
  type BundleInput,
  type BundleLabels,
} from "../components/investigationBundle";
import { MASK_PLACEHOLDER, resolveMaskedColumns } from "../components/columnMask";
import type { TableColumnInfo } from "../api/tauri";

/**
 * 調査バンドル (#745) の HTML 生成。共有ファイルは受け手のブラウザで開かれるため、
 * エスケープ (XSS 相当の混入防止)・外部リソース非参照・秘密情報非同梱・機微カラム
 * マスクの尊重を固定する。
 */

const LABELS: BundleLabels = {
  title: "Bundle",
  notice: "Generated by noobDB",
  sectionMeta: "Context",
  sectionSql: "Query",
  sectionResult: "Result",
  sectionSchema: "Schema",
  sectionPlan: "Plan",
  generatedAt: "Generated",
  executedAt: "Executed",
  profile: "Connection",
  driver: "Driver",
  database: "Database",
  host: "Host",
  rows: "Rows",
  elapsed: "Elapsed",
  partial: "Partial",
  masked: "masked",
  sortHint: "Sort",
  noSql: "no sql",
  noRows: "no rows",
  unavailable: "unavailable",
  colName: "Column",
  colType: "Type",
  colNullable: "Nullable",
  colKey: "Key",
  colDefault: "Default",
  colExtra: "Extra",
  yes: "YES",
  no: "NO",
};

function input(over: Partial<BundleInput> = {}): BundleInput {
  return {
    sql: "SELECT id, name FROM users WHERE id = 1",
    columns: [
      { name: "id", type_name: "INT" },
      { name: "name", type_name: "VARCHAR" },
    ],
    rows: [
      [1, "alice"],
      [2, null],
    ],
    maskedColumns: null,
    meta: {
      generatedAt: new Date(2026, 0, 2, 3, 4, 5),
      executedAt: new Date(2026, 0, 2, 3, 0, 0),
      profileName: "prod-replica",
      driver: "mysql",
      database: "appdb",
      host: null,
      elapsedMs: 42,
      partial: false,
    },
    labels: LABELS,
    ...over,
  };
}

/** HTML から要素・属性の開始タグ名を列挙する (データ由来のタグ混入検出用)。 */
function tagNames(html: string): string[] {
  return [...html.matchAll(/<([a-zA-Z][a-zA-Z0-9-]*)[\s>/]/g)].map((m) => m[1].toLowerCase());
}

describe("escapeHtml", () => {
  it("& < > \" ' をすべてエスケープする", () => {
    expect(escapeHtml(`<a href="x" onclick='y'>&</a>`)).toBe(
      "&lt;a href=&quot;x&quot; onclick=&#39;y&#39;&gt;&amp;&lt;/a&gt;",
    );
  });
  it("& を最初に処理して二重エスケープにしない", () => {
    expect(escapeHtml("&lt;")).toBe("&amp;lt;");
  });
});

describe("tokenizeSql / highlightSqlHtml", () => {
  const samples = [
    "SELECT 'it''s', \"col\"\"x\", `b``t`, [a]]b] -- c\n/* d */ 1.5e3 FROM t",
    "select '<unterminated",
    "/* unterminated",
    "SELECT '\\'' , $1, ñame FROM ユーザ",
    "",
  ];
  it.each(samples)("連結すると元の SQL に戻る: %s", (sql) => {
    expect(tokenizeSql(sql).map((t) => t.text).join("")).toBe(sql);
  });

  it("キーワード・文字列・数値・コメントを色分けする", () => {
    const html = highlightSqlHtml("SELECT 'a', 1 -- x");
    expect(html).toContain('<span class="k">SELECT</span>');
    expect(html).toContain(`<span class="s">&#39;a&#39;</span>`);
    expect(html).toContain('<span class="n">1</span>');
    expect(html).toContain('<span class="c">-- x</span>');
  });

  it("SQL 中の <script> はエスケープされタグにならない (XSS)", () => {
    const html = highlightSqlHtml("SELECT '</code></pre><script>alert(1)</script>' AS x -- <img src=x onerror=alert(1)>");
    expect(html).not.toContain("<script");
    expect(html).not.toContain("<img");
    expect(html).toContain("&lt;script&gt;alert(1)&lt;/script&gt;");
    expect(tagNames(html).every((t) => t === "span")).toBe(true);
  });
});

describe("extractReferencedTables", () => {
  it("FROM / JOIN の参照テーブルを抽出する (エイリアス・修飾・引用符)", () => {
    expect(
      extractReferencedTables(
        "SELECT * FROM users u JOIN `app`.`orders` AS o ON o.uid = u.id LEFT JOIN \"public\".\"items\" i ON 1=1",
      ),
    ).toEqual([
      { database: null, table: "users" },
      { database: "app", table: "orders" },
      { database: "public", table: "items" },
    ]);
  });

  it("FROM のカンマ区切りも拾い、重複は除く", () => {
    expect(extractReferencedTables("select * from a x, b as y, a where 1=1")).toEqual([
      { database: null, table: "a" },
      { database: null, table: "b" },
    ]);
  });

  it("文字列・コメント中の FROM と、サブクエリ・関数呼び出しは無視する", () => {
    expect(
      extractReferencedTables(
        "select 'from fake' -- from nope\n from (select 1) s join generate_series(1,3) g on true join real_t r on true",
      ),
    ).toEqual([{ database: null, table: "real_t" }]);
  });

  it("MSSQL の [db].[dbo].[t] は最後をテーブル、1 つ前を database とする", () => {
    expect(extractReferencedTables("SELECT TOP 5 * FROM [db].[dbo].[t]")).toEqual([
      { database: "dbo", table: "t" },
    ]);
  });

  it("上限件数で打ち切る", () => {
    expect(extractReferencedTables("select * from a join b on 1 join c on 1", 2)).toHaveLength(2);
  });
});

describe("bundleSchemaTargets / loadBundleSchema", () => {
  it("元テーブルが分かっていればそれだけ、無ければ SQL から抽出", () => {
    expect(bundleSchemaTargets("select * from x", "db", "t")).toEqual([{ database: "db", table: "t" }]);
    expect(bundleSchemaTargets("select * from x", "db", null)).toEqual([{ database: null, table: "x" }]);
    expect(bundleSchemaTargets(null, "db", null)).toEqual([]);
  });

  it("1 テーブルの失敗は error として残し、他は取得する", async () => {
    const cols: TableColumnInfo[] = [
      { name: "id", data_type: "int", nullable: false, key: "PRI", default: null, extra: "", fk: null } as unknown as TableColumnInfo,
    ];
    const describe = vi.fn(async (_db: string, table: string) => {
      if (table === "bad") throw new Error("boom");
      return cols;
    });
    const out = await loadBundleSchema(
      [
        { database: null, table: "good" },
        { database: "other", table: "bad" },
      ],
      "appdb",
      describe,
    );
    expect(describe).toHaveBeenCalledWith("appdb", "good");
    expect(describe).toHaveBeenCalledWith("other", "bad");
    expect(out[0]).toEqual({ database: "appdb", table: "good", columns: cols });
    expect(out[1].columns).toBeNull();
    expect(out[1].error).toContain("boom");
  });
});

describe("bundlePlanSupported", () => {
  it("EXPLAIN タブと同じ方言だけ対応", () => {
    expect(bundlePlanSupported("mysql")).toBe(true);
    expect(bundlePlanSupported("postgres")).toBe(true);
    expect(bundlePlanSupported("sqlite")).toBe(true);
    expect(bundlePlanSupported("mssql")).toBe(false);
    expect(bundlePlanSupported("duckdb")).toBe(false);
    expect(bundlePlanSupported(undefined)).toBe(false);
  });
});

describe("buildInvestigationBundleHtml", () => {
  it("クエリ・結果・メタ情報を含む完全な HTML 文書を返す", () => {
    const html = buildInvestigationBundleHtml(input());
    expect(html.startsWith("<!DOCTYPE html>")).toBe(true);
    expect(html).toContain("</html>");
    expect(html).toContain('<meta charset="utf-8">');
    expect(html).toContain("Generated by noobDB");
    expect(html).toContain("prod-replica");
    expect(html).toContain("appdb");
    expect(html).toContain("mysql");
    expect(html).toContain("42 ms");
    expect(html).toContain("2026-01-02 03:04:05");
    expect(html).toContain("2026-01-02 03:00:00");
    expect(html).toContain('<span class="k">SELECT</span>');
    expect(html).toContain("<td>alice</td>");
    expect(html).toContain('<td class="null">NULL</td>');
    expect(html).toContain('<td class="num">1</td>');
    expect(html).toContain('class="grid sortable"');
  });

  it("外部リソースを一切参照しない (CSP で default-src 'none' を宣言)", () => {
    const html = buildInvestigationBundleHtml(input());
    expect(html).toContain(`http-equiv="Content-Security-Policy"`);
    expect(BUNDLE_CSP).toContain("default-src 'none'");
    expect(BUNDLE_CSP).not.toMatch(/https?:/);
    // src= / href= / @import / url(http…) の外部参照が無い。
    expect(html).not.toMatch(/\s(?:src|href)\s*=/i);
    expect(html).not.toMatch(/@import/i);
    expect(html).not.toMatch(/url\(\s*['"]?(?:https?:)?\/\//i);
    expect(html).not.toMatch(/<link\b/i);
  });

  it("セル値・列名・SQL・メタ情報の HTML を必ずエスケープする (XSS)", () => {
    const evil = `</td></tr></tbody></table><script>alert("x")</script><img src=x onerror=alert(1)>`;
    const html = buildInvestigationBundleHtml(
      input({
        sql: `SELECT '${evil}' AS "<b>x</b>"`,
        columns: [
          { name: `<svg onload=alert(1)>`, type_name: `<i>t</i>` },
          { name: "v", type_name: "TEXT" },
        ],
        rows: [[evil, `"' onmouseover=alert(1) x="`]],
        meta: {
          ...input().meta,
          profileName: `<script>p</script>`,
          database: `"><script>d</script>`,
          driver: "mysql",
        },
        schema: [
          {
            database: "<s>",
            table: evil,
            columns: [
              {
                name: evil,
                data_type: evil,
                nullable: true,
                key: evil,
                default: evil,
                extra: evil,
              } as unknown as TableColumnInfo,
            ],
          },
          { database: null, table: "missing", columns: null, error: evil },
        ],
        plan: { result: { columns: [{ name: "p", type_name: "" }], rows: [[evil]], rows_affected: 0, elapsed_ms: 0 } },
        labels: { ...LABELS, title: evil, notice: evil },
      }),
    );
    // 生成物に含まれる <script> は末尾の固定ソートスクリプト 1 つだけ。
    expect(html.match(/<script/gi)).toHaveLength(1);
    expect(html).not.toMatch(/<img\b/i);
    expect(html).not.toMatch(/<svg\b/i);
    expect(html).not.toMatch(/<i>t<\/i>/);
    // イベントハンドラ属性を持つ実タグが無い (エスケープ済みテキスト中の文字列は無害)。
    expect(html).not.toMatch(/<[a-z][^>]*\son\w+\s*=/i);
    // 出現するタグは生成器が出す固定の集合だけ。
    const allowed = new Set([
      "html", "head", "meta", "title", "style", "body", "header", "h1", "h2", "h3", "p", "main",
      "section", "table", "thead", "tbody", "tr", "th", "td", "div", "pre", "code", "span",
      "footer", "script",
    ]);
    expect(tagNames(html).filter((t) => !allowed.has(t))).toEqual([]);
    expect(html).toContain("&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt;");
  });

  it("DOM に読み込んでもデータ由来の要素・スクリプトが生えない", () => {
    const evil = `<script>window.__pwned=1</script><img src=x onerror="window.__pwned=1">`;
    const html = buildInvestigationBundleHtml(
      input({ rows: [[1, evil]], sql: `select '${evil}'`, meta: { ...input().meta, profileName: evil } }),
    );
    const doc = new DOMParser().parseFromString(html, "text/html");
    expect(doc.querySelectorAll("script")).toHaveLength(1);
    expect(doc.querySelectorAll("img")).toHaveLength(0);
    const cell = doc.querySelector("table.sortable tbody tr td:nth-child(2)");
    expect(cell?.textContent).toBe(evil);
  });

  it("接続の秘密情報は受け取らず、ホスト名は渡されたときだけ出す", () => {
    const without = buildInvestigationBundleHtml(input());
    expect(without).not.toContain(">Host<");
    const withHost = buildInvestigationBundleHtml(
      input({ meta: { ...input().meta, host: "db.internal.example" } }),
    );
    expect(withHost).toContain(">Host<");
    expect(withHost).toContain("db.internal.example");
    // BundleMeta に password / connection string のフィールドは存在しない
    // (型で持たない) — 生成物にも該当の見出しが無い。
    expect(withHost.toLowerCase()).not.toContain("password");
  });

  it("機微カラムマスクの対象列は伏せ字で出し、実値を含めない", () => {
    const columns = [
      { name: "id", type_name: "INT" },
      { name: "user_email", type_name: "VARCHAR" },
      { name: "api_token", type_name: "VARCHAR" },
    ];
    const masked = resolveMaskedColumns(
      columns.map((c) => c.name),
      { enabled: true, patterns: ["email", "token"], overrides: {} },
    );
    const html = buildInvestigationBundleHtml(
      input({
        columns,
        rows: [[1, "alice@example.com", "sk-SECRET-123"]],
        maskedColumns: masked,
      }),
    );
    expect(html).not.toContain("alice@example.com");
    expect(html).not.toContain("sk-SECRET-123");
    expect(html.split(`<td class="mask">${MASK_PLACEHOLDER}</td>`)).toHaveLength(3);
    expect(html).toContain("user_email, api_token");
  });

  it("マスク無効なら値をそのまま出す", () => {
    const html = buildInvestigationBundleHtml(
      input({ rows: [[1, "alice@example.com"]], maskedColumns: null }),
    );
    expect(html).toContain("alice@example.com");
    expect(html).not.toContain('class="mask"');
  });

  it("スキーマ定義・実行計画は渡したときだけ同梱し、JSON プランは整形する", () => {
    const plain = buildInvestigationBundleHtml(input());
    expect(plain).not.toContain(">Schema<");
    expect(plain).not.toContain(">Plan<");

    const html = buildInvestigationBundleHtml(
      input({
        schema: [
          {
            database: "appdb",
            table: "users",
            columns: [
              { name: "id", data_type: "int", nullable: false, key: "PRI", default: null, extra: "auto_increment" } as unknown as TableColumnInfo,
            ],
          },
        ],
        plan: {
          result: {
            columns: [{ name: "EXPLAIN", type_name: "JSON" }],
            rows: [['{"query_block":{"select_id":1}}']],
            rows_affected: 0,
            elapsed_ms: 1,
          },
        },
      }),
    );
    expect(html).toContain(">Schema<");
    expect(html).toContain("appdb.users");
    expect(html).toContain("auto_increment");
    expect(html).toContain(">Plan<");
    expect(html).toContain('<pre class="plan">{\n  &quot;query_block&quot;: {\n    &quot;select_id&quot;: 1\n  }\n}</pre>');
  });

  it("実行計画の取得失敗は理由付きで表示する", () => {
    const html = buildInvestigationBundleHtml(input({ plan: { result: null, error: "denied" } }));
    expect(html).toContain("unavailable: denied");
  });

  it("部分結果なら注記を出す", () => {
    const html = buildInvestigationBundleHtml(input({ meta: { ...input().meta, partial: true } }));
    expect(html).toContain('<p class="notice">Partial</p>');
  });

  it("lang は安全な値だけ受け付ける", () => {
    expect(buildInvestigationBundleHtml(input({ lang: "en" }))).toContain('<html lang="en">');
    expect(buildInvestigationBundleHtml(input({ lang: `"><script>` }))).toContain('<html lang="ja">');
  });
});
