import { describe, expect, it } from "vitest";
import type { SyncPlan } from "../api/tauri";
import {
  buildMigrationFile,
  buildMigrationHeader,
  defaultMigrationName,
  migrationFileNames,
  migrationVersion,
  renderMigrationStatements,
  renderMigrationWarnings,
  sanitizeMigrationName,
  type MigrationEndpointMeta,
} from "../components/migrationExport";

describe("sanitizeMigrationName", () => {
  it("keeps alphanumeric and underscore untouched", () => {
    expect(sanitizeMigrationName("add_users_table")).toBe("add_users_table");
  });

  it("replaces spaces and punctuation with a single underscore", () => {
    expect(sanitizeMigrationName("add users - table!!")).toBe("add_users_table");
  });

  it("collapses consecutive separators and trims leading/trailing underscores", () => {
    expect(sanitizeMigrationName("  --add__users--  ")).toBe("add_users");
  });

  it("falls back to 'migration' when nothing alphanumeric remains", () => {
    expect(sanitizeMigrationName("スキーマ同期")).toBe("migration");
    expect(sanitizeMigrationName("   ")).toBe("migration");
  });
});

describe("defaultMigrationName", () => {
  it("combines distinct source/target database names", () => {
    expect(defaultMigrationName("shop_staging", "shop_prod")).toBe("shop_staging_to_shop_prod");
  });

  it("uses a single name when both sides share a database", () => {
    expect(defaultMigrationName("shop", "shop")).toBe("shop");
  });

  it("falls back to schema_sync when both are empty", () => {
    expect(defaultMigrationName("", "")).toBe("schema_sync");
  });
});

describe("migrationVersion", () => {
  it("formats a UTC timestamp as yyyyMMddHHmmss", () => {
    const date = new Date(Date.UTC(2026, 6, 28, 9, 5, 3));
    expect(migrationVersion(date)).toBe("20260728090503");
  });

  it("pads single-digit month/day/time components", () => {
    const date = new Date(Date.UTC(2026, 0, 2, 3, 4, 5));
    expect(migrationVersion(date)).toBe("20260102030405");
  });
});

describe("migrationFileNames", () => {
  const version = "20260728090503";
  const name = "add_users_table";

  it("builds Flyway V/U prefixed names", () => {
    expect(migrationFileNames("flyway", version, name)).toEqual({
      up: `V${version}__${name}.sql`,
      down: `U${version}__${name}.sql`,
    });
  });

  it("builds golang-migrate .up/.down names", () => {
    expect(migrationFileNames("golang-migrate", version, name)).toEqual({
      up: `${version}_${name}.up.sql`,
      down: `${version}_${name}.down.sql`,
    });
  });

  it("builds sqlx -r style .up/.down names", () => {
    expect(migrationFileNames("sqlx", version, name)).toEqual({
      up: `${version}_${name}.up.sql`,
      down: `${version}_${name}.down.sql`,
    });
  });

  it("builds generic names without a version", () => {
    expect(migrationFileNames("generic", version, name)).toEqual({
      up: `${name}.up.sql`,
      down: `${name}.down.sql`,
    });
  });
});

function meta(overrides: Partial<MigrationEndpointMeta> = {}): MigrationEndpointMeta {
  return {
    profileName: "Staging",
    driver: "mysql",
    database: "shop",
    host: "127.0.0.1",
    port: 3306,
    filePath: null,
    ...overrides,
  };
}

describe("buildMigrationHeader", () => {
  it("includes the generation timestamp, direction, format and both endpoints", () => {
    const header = buildMigrationHeader({
      generatedAt: new Date(Date.UTC(2026, 6, 28, 9, 5, 3)),
      format: "flyway",
      direction: "up",
      source: meta({ profileName: "Source DB", database: "shop_staging" }),
      target: meta({ profileName: "Target DB", database: "shop_prod", port: 3307 }),
    });
    expect(header).toContain("Generated by noobDB");
    expect(header).toContain("2026-07-28T09:05:03");
    expect(header).toContain("Direction: up");
    expect(header).toContain("Format: flyway");
    expect(header).toContain("Source DB");
    expect(header).toContain("shop_staging");
    expect(header).toContain("Target DB");
    expect(header).toContain("shop_prod");
  });

  it("describes SQLite endpoints by file path instead of host:port", () => {
    const header = buildMigrationHeader({
      generatedAt: new Date(Date.UTC(2026, 6, 28, 9, 5, 3)),
      format: "generic",
      direction: "down",
      source: meta({ driver: "sqlite", host: null, port: null, filePath: "/tmp/a.sqlite" }),
      target: meta({ driver: "sqlite", host: null, port: null, filePath: "/tmp/b.sqlite" }),
    });
    expect(header).toContain("/tmp/a.sqlite");
    expect(header).toContain("/tmp/b.sqlite");
    expect(header).not.toContain("null:null");
  });
});

describe("renderMigrationStatements", () => {
  it("joins statements with a trailing semicolon", () => {
    const sql = renderMigrationStatements([
      { sql: "CREATE TABLE t (id INT)", table: "t", kind: "create_table", destructive: false },
      { sql: "ALTER TABLE t ADD COLUMN c INT", table: "t", kind: "add_column", destructive: false },
    ]);
    expect(sql).toBe(
      "CREATE TABLE t (id INT);\n\nALTER TABLE t ADD COLUMN c INT;",
    );
  });

  it("renders a placeholder comment when there are no statements", () => {
    expect(renderMigrationStatements([])).toBe("-- (no statements)");
  });
});

describe("renderMigrationWarnings", () => {
  it("returns an empty string when there are no warnings", () => {
    expect(renderMigrationWarnings([])).toBe("");
  });

  it("comments out each warning line, including multi-line warnings", () => {
    const rendered = renderMigrationWarnings([
      "sqlite cannot alter columns in place: t.c",
      "line one\nline two",
    ]);
    expect(rendered).toContain("-- Warnings");
    expect(rendered).toContain("--   sqlite cannot alter columns in place: t.c");
    expect(rendered).toContain("--   line one");
    expect(rendered).toContain("--   line two");
  });
});

describe("buildMigrationFile", () => {
  it("combines header, statements and warnings into one file with a trailing newline", () => {
    const plan: SyncPlan = {
      statements: [
        { sql: "CREATE TABLE t (id INT)", table: "t", kind: "create_table", destructive: false },
      ],
      warnings: ["sqlite cannot alter columns in place: t.c"],
    };
    const header = "-- header line";
    const content = buildMigrationFile(header, plan);
    expect(content.startsWith("-- header line\n\nCREATE TABLE t (id INT);")).toBe(true);
    expect(content).toContain("-- Warnings");
    expect(content.endsWith("\n")).toBe(true);
  });

  it("omits the warnings block entirely when there are none", () => {
    const plan: SyncPlan = { statements: [], warnings: [] };
    const content = buildMigrationFile("-- header", plan);
    expect(content).toBe("-- header\n\n-- (no statements)\n");
  });
});
