// テストデータ生成の AI モード (#698) の純ロジック: コンテキスト組み立て・プロンプト・応答パース・決定的な展開。
// 副作用 (IPC・状態管理) は `components/TestDataModal.tsx` が持つ。
//
// ハイブリッド生成でトークンを抑える: AI には「列ごとの値パターン (候補値のリスト) と列間の整合ルール」
// だけを返させ、行への展開は `mulberry32` のシードで決定的にフロントで行う。
// 送るのはテーブル名・列名・型・NULL 可否・キー種別・ENUM 候補・外部キー・件数・ロケール・ユーザが書いたヒントだけで、
// 既存の実データ・サンプル値・デフォルト値・列コメントは送らない。

import { z } from "zod";
import type { CellValue, TableColumnInfo } from "../api/tauri";
import {
  activeSpecs,
  classifyDataType,
  coerceFixedValue,
  generateRows,
  isAutoGenerated,
  mulberry32,
  parseEnumChoices,
  type ColumnGenSpec,
} from "../components/testDataGen";
import { dialectLabel } from "./errorExplain";

/** 1 列あたりに AI へ求める候補値 / テンプレートの最大数。 */
export const TEST_DATA_MAX_CHOICES = 50;

/** ヒント 1 行の最大文字数 (長文を送らない)。 */
export const TEST_DATA_HINT_MAX = 200;

/** 構造化出力で受け取る応答の形 (`run_ai_request` の `format` にそのまま渡す)。 */
export const TEST_DATA_FORMAT = {
  type: "json_schema",
  schema: {
    type: "object",
    properties: {
      columns: {
        type: "array",
        items: {
          type: "object",
          properties: {
            name: { type: "string" },
            kind: { type: "string", enum: ["choices", "pattern", "skip"] },
            choices: { type: "array", items: { type: "string" } },
            notes: { type: "string" },
          },
          required: ["name", "kind", "choices", "notes"],
          additionalProperties: false,
        },
      },
      consistency_rules: {
        type: "array",
        items: {
          type: "object",
          properties: {
            columns: { type: "array", items: { type: "string" } },
            description: { type: "string" },
          },
          required: ["columns", "description"],
          additionalProperties: false,
        },
      },
    },
    required: ["columns", "consistency_rules"],
    additionalProperties: false,
  },
} as const;

const responseSchema = z.object({
  columns: z.array(
    z.object({
      name: z.string(),
      kind: z.enum(["choices", "pattern", "skip"]),
      choices: z.array(z.string()),
      notes: z.string(),
    }),
  ),
  consistency_rules: z.array(z.object({ columns: z.array(z.string()), description: z.string() })),
});
export type TestDataAiResponse = z.infer<typeof responseSchema>;

export type ParsedTestDataResponse = { ok: true; value: TestDataAiResponse } | { ok: false; raw: string };

/** ストリームで結合した本文を JSON として解釈する。失敗時は本文をそのまま返す。 */
export function parseTestDataResponse(text: string): ParsedTestDataResponse {
  let body = text.trim();
  const fenced = /^```(?:json)?\s*([\s\S]*?)\s*```$/.exec(body);
  if (fenced) body = fenced[1];
  try {
    const parsed = responseSchema.safeParse(JSON.parse(body));
    if (parsed.success) return { ok: true, value: parsed.data };
  } catch {
    /* JSON でない */
  }
  return { ok: false, raw: text };
}

/** AI に値パターンを作らせる列。 */
export interface TestDataAiColumn {
  name: string;
  dataType: string;
  nullable: boolean;
  primaryKey: boolean;
  unique: boolean;
  /** ENUM / SET の宣言候補 (スキーマ由来)。 */
  enumChoices: string[] | null;
  /** ユーザが任意で書いたヒント (1 行)。 */
  hint: string;
}

/** AI へ「参照先の既存行から埋める」と伝える外部キー列 (生成はさせない)。 */
export interface TestDataAiReference {
  column: string;
  table: string;
  refColumn: string | null;
}

export interface TestDataAiContext {
  columns: TestDataAiColumn[];
  references: TestDataAiReference[];
}

/** 方針が「ランダム系 / 列挙」の列にだけ AI の値を当てる (固定値・連番・UUID・参照先・対象外はユーザ指定を優先)。 */
const AI_ELIGIBLE_STRATEGIES = new Set<ColumnGenSpec["strategy"]>([
  "randomString",
  "randomNumber",
  "randomDate",
  "randomBool",
  "choice",
]);

export function isAiEligible(spec: ColumnGenSpec): boolean {
  return AI_ELIGIBLE_STRATEGIES.has(spec.strategy) && spec.kind !== "binary";
}

function isUniqueKey(key: string): boolean {
  const k = key.toUpperCase();
  return k.includes("PRI") || k.includes("UNI");
}

/** 主キー・UNIQUE 列の名前 (展開時に一意化する)。 */
export function uniqueColumnNames(cols: TableColumnInfo[]): string[] {
  return cols.filter((c) => isUniqueKey(c.key)).map((c) => c.name);
}

/**
 * `describe_table` の結果とユーザの現在の方針から、AI に送る列情報を作る。
 * 自動採番 / 生成列は含めない。デフォルト値・列コメントは読まない。
 */
export function buildTestDataAiContext(
  cols: TableColumnInfo[],
  specs: ColumnGenSpec[],
  hints: Record<string, string>,
): TestDataAiContext {
  const columns: TestDataAiColumn[] = [];
  const references: TestDataAiReference[] = [];
  cols.forEach((col, i) => {
    const spec = specs[i];
    if (!spec || spec.strategy === "omit" || isAutoGenerated(col)) return;
    if (col.referenced_table) {
      references.push({ column: col.name, table: col.referenced_table, refColumn: col.referenced_column });
    }
    if (!isAiEligible(spec)) return;
    columns.push({
      name: col.name,
      dataType: col.data_type,
      nullable: col.nullable,
      primaryKey: col.key.toUpperCase().includes("PRI"),
      unique: isUniqueKey(col.key),
      enumChoices: parseEnumChoices(col.data_type),
      hint: (hints[col.name] ?? "").trim().replace(/\s+/g, " ").slice(0, TEST_DATA_HINT_MAX),
    });
  });
  return { columns, references };
}

export interface TestDataSystemInput {
  driver: string;
  table: string;
  rowCount: number;
  locale: "ja" | "en";
  context: TestDataAiContext;
}

function describeColumn(c: TestDataAiColumn): string {
  const parts = [`- ${c.name}: ${c.dataType}`, c.nullable ? "NULL" : "NOT NULL"];
  if (c.primaryKey) parts.push("PRIMARY KEY");
  else if (c.unique) parts.push("UNIQUE");
  let line = parts.join(" ");
  if (c.enumChoices && c.enumChoices.length > 0) {
    line += ` | allowed values: ${c.enumChoices.join(" / ")}`;
  }
  if (c.hint !== "") line += ` | user hint: ${c.hint}`;
  return line;
}

/** system プロンプト。スキーマ・件数・ロケールだけを含み、行データは含めない。 */
export function buildTestDataSystem(input: TestDataSystemInput): string {
  const lang = input.locale === "ja" ? "Japanese" : "English";
  const dialect = dialectLabel(input.driver);
  const lines = [
    `You design realistic test data for a ${dialect} table, using only its schema.`,
    `The caller will insert about ${input.rowCount} rows. You do NOT write rows: you return, per column, a compact list of realistic values or templates, and the caller expands them into rows.`,
    `Write human-readable values (names, addresses, product names, statuses, free text) in ${lang}, appropriate for the column names and the user hints. Write notes in ${lang}.`,
    "Answer only with the JSON object described by the schema.",
    `columns: one entry per column listed below, using the exact column name. kind "choices": up to ${TEST_DATA_MAX_CHOICES} distinct realistic values. kind "pattern": up to ${TEST_DATA_MAX_CHOICES} templates in which {n} is replaced by the 1-based row number (use for emails, codes, order numbers). kind "skip": the column cannot be meaningfully generated, so leave it to a generic generator (choices: []). notes: a short remark, or an empty string.`,
    "Every value is a string. Numbers are plain digits (no thousands separators or units), booleans are true/false, dates are YYYY-MM-DD, date-times are YYYY-MM-DD HH:MM:SS, times are HH:MM:SS. Respect the declared type, length and NOT NULL.",
    "For columns with allowed values, use only those values.",
    'consistency_rules: groups of columns whose values must correspond row by row (for example product_name and unit_price, or country and city). For every column in one rule, return "choices" lists of exactly the same length where the i-th entry of each list belongs to the same logical record. Columns that are not in any rule are independent. Use an empty array when there are no such relations.',
    "Use only the listed columns; never invent names. You are given only the schema: you never see real rows, so do not assume or reproduce any existing data.",
    "",
    `Table: ${input.table}`,
    "Columns to design:",
    ...input.context.columns.map(describeColumn),
  ];
  if (input.context.references.length > 0) {
    lines.push("");
    lines.push("Foreign key columns (filled by the caller from existing parent rows; do not design them):");
    for (const r of input.context.references) {
      lines.push(`- ${r.column} -> ${r.table}.${r.refColumn ?? "?"}`);
    }
  }
  return lines.join("\n");
}

/** ユーザプロンプト (スキーマ以外の情報は含めない)。 */
export function buildTestDataPrompt(table: string, rowCount: number): string {
  return `Design the value lists for table "${table}" (about ${rowCount} rows).`;
}

export interface TestDataSendSummary {
  table: string;
  columns: number;
  foreignKeys: number;
  rows: number;
  locale: "ja" | "en";
}

/** 送信前に 1 行で見せる内容の件数。 */
export function summarizeTestDataSend(
  table: string,
  context: TestDataAiContext,
  rowCount: number,
  locale: "ja" | "en",
): TestDataSendSummary {
  return { table, columns: context.columns.length, foreignKeys: context.references.length, rows: rowCount, locale };
}

/** 応答の検証で見つかった注意点 (表示は呼び出し側が i18n する)。 */
export interface TestDataPlanWarning {
  code: "unknownColumn" | "unusableChoices" | "misaligned";
  columns: string[];
}

export interface AiColumnPlan {
  kind: "choices" | "pattern";
  choices: string[];
}

export interface TestDataAiPlan {
  columns: Record<string, AiColumnPlan>;
  /** 行ごとに同じ添字で選ぶ列のグループ (整合ルール)。2 列以上のものだけ。 */
  groups: string[][];
  rules: { columns: string[]; description: string }[];
  notes: Record<string, string>;
  warnings: TestDataPlanWarning[];
}

function isNumericText(s: string): boolean {
  return s.trim() !== "" && Number.isFinite(Number(s.trim()));
}

/** 列の型に使える候補だけを残す。 */
function usableChoices(col: TestDataAiColumn, kind: AiColumnPlan["kind"], raw: string[]): string[] {
  const colKind = classifyDataType(col.dataType);
  let out = raw.map((c) => c.trim()).filter((c) => c !== "");
  if (col.enumChoices && col.enumChoices.length > 0) {
    const allowed = new Set(col.enumChoices);
    out = out.filter((c) => allowed.has(c));
  } else if (colKind === "number" || colKind === "decimal") {
    out = kind === "pattern" ? [] : out.filter(isNumericText);
  } else if (colKind === "bool") {
    out = kind === "pattern" ? [] : out.filter((c) => /^(true|false|0|1)$/i.test(c));
  }
  return out.slice(0, TEST_DATA_MAX_CHOICES);
}

/**
 * 応答を検証して展開用の計画にする。未知の列は捨て、型に合わない候補は除き、
 * 整合ルールは候補の個数が揃っているときだけ「同じ添字で選ぶ」扱いにする。
 */
export function buildTestDataPlan(resp: TestDataAiResponse, columns: TestDataAiColumn[]): TestDataAiPlan {
  const byName = new Map(columns.map((c) => [c.name, c]));
  const plan: TestDataAiPlan = { columns: {}, groups: [], rules: [], notes: {}, warnings: [] };
  const unknown: string[] = [];
  const unusable: string[] = [];
  for (const entry of resp.columns) {
    const col = byName.get(entry.name);
    if (!col) {
      unknown.push(entry.name);
      continue;
    }
    if (entry.notes.trim() !== "") plan.notes[entry.name] = entry.notes.trim();
    if (entry.kind === "skip") continue;
    const choices = usableChoices(col, entry.kind, entry.choices);
    if (choices.length === 0) {
      unusable.push(entry.name);
      continue;
    }
    plan.columns[entry.name] = { kind: entry.kind, choices };
  }
  if (unknown.length > 0) plan.warnings.push({ code: "unknownColumn", columns: unknown });
  if (unusable.length > 0) plan.warnings.push({ code: "unusableChoices", columns: unusable });

  // 整合ルール → 添字を揃える列のグループ (union-find)。
  const parent = new Map<string, string>();
  const find = (x: string): string => {
    let r = x;
    while ((parent.get(r) ?? r) !== r) r = parent.get(r) ?? r;
    return r;
  };
  const misaligned = new Set<string>();
  for (const rule of resp.consistency_rules) {
    const names = [...new Set(rule.columns)].filter((n) => plan.columns[n] !== undefined);
    if (names.length < 2) continue;
    const len = plan.columns[names[0]].choices.length;
    if (names.some((n) => plan.columns[n].choices.length !== len)) {
      for (const n of names) misaligned.add(n);
      continue;
    }
    plan.rules.push({ columns: names, description: rule.description });
    for (const n of names) if (!parent.has(n)) parent.set(n, n);
    for (const n of names.slice(1)) parent.set(find(n), find(names[0]));
  }
  if (misaligned.size > 0) plan.warnings.push({ code: "misaligned", columns: [...misaligned] });
  const groups = new Map<string, string[]>();
  for (const name of parent.keys()) {
    const root = find(name);
    groups.set(root, [...(groups.get(root) ?? []), name]);
  }
  // 別ルールの合流で個数が食い違ったグループは、ばらして独立に選ぶ。
  for (const g of groups.values()) {
    const len = plan.columns[g[0]].choices.length;
    if (g.length >= 2 && g.every((n) => plan.columns[n].choices.length === len)) plan.groups.push(g);
  }
  return plan;
}

/** 1 テーブル分の展開入力。 */
export interface AiTableInput {
  table: string;
  /** `inferColumnSpec` + ユーザ編集後の方針 (FK 候補の取得済み値を含む)。 */
  specs: ColumnGenSpec[];
  plan: TestDataAiPlan | null;
  /** 主キー / UNIQUE 列 (展開時に一意化する)。 */
  uniqueColumns: string[];
  count: number;
}

export interface AiTableRows {
  /** `activeSpecs(specs)` と同じ順の列名。 */
  columns: string[];
  rows: CellValue[][];
}

function deriveSeed(seed: number, salt: number): number {
  return (seed ^ Math.imul(salt + 1, 0x9e3779b1)) >>> 0;
}

function shuffledOrder(n: number, rng: () => number): number[] {
  const order = Array.from({ length: n }, (_, i) => i);
  for (let i = n - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [order[i], order[j]] = [order[j], order[i]];
  }
  return order;
}

/** 一意制約のある列で、すでに使った値と衝突したら文字列は `_2` 形式、数値は最大値+1 にずらす。 */
function makeUniquifier(): (v: CellValue) => CellValue {
  const used = new Set<string>();
  let maxNum = Number.NEGATIVE_INFINITY;
  return (v) => {
    if (v === null) return v;
    if (typeof v === "number") {
      let n = v;
      if (used.has(String(n))) n = Math.floor(Math.max(maxNum, n)) + 1;
      used.add(String(n));
      maxNum = Math.max(maxNum, n);
      return n;
    }
    const base = String(v);
    let s = base;
    for (let k = 2; used.has(s); k++) s = `${base}_${k}`;
    used.add(s);
    return s;
  };
}

function aiColumnValues(
  spec: ColumnGenSpec,
  plan: AiColumnPlan,
  idxs: number[],
  seed: number,
  unique: boolean,
): CellValue[] {
  const nullRng = mulberry32(deriveSeed(seed, 0x4e554c4c));
  const uniq = unique ? makeUniquifier() : null;
  return idxs.map((idx, i) => {
    if (spec.nullRate > 0 && nullRng() < spec.nullRate) return null;
    let raw = plan.choices[idx];
    if (plan.kind === "pattern") raw = raw.replace(/\{n\}/g, String(i + 1));
    const v = coerceFixedValue(raw, spec.kind);
    return uniq ? uniq(v) : v;
  });
}

function expandTable(
  input: AiTableInput,
  seed: number,
  parentValues: Map<string, CellValue[]>,
): AiTableRows {
  const active = activeSpecs(input.specs).map((spec) => {
    // 親も同時に生成する場合: 取得済みの候補が無い FK 列は親の生成値から配る。
    if (spec.strategy === "fkRef" && spec.choices.length === 0 && spec.fkTable && spec.fkColumn) {
      const vals = parentValues.get(`${spec.fkTable}\u0000${spec.fkColumn}`);
      if (vals) return { ...spec, choices: vals };
    }
    return spec;
  });
  const unique = new Set(input.uniqueColumns);
  const plan = input.plan;
  const colValues: CellValue[][] = new Array(active.length);

  // AI 値を当てる列 (計画にあり、方針が AI 対象のもの) と、そのグループ。
  const aiIndex = new Map<string, number>();
  active.forEach((s, i) => {
    if (plan && plan.columns[s.column] && isAiEligible(s)) aiIndex.set(s.column, i);
  });
  const groups: string[][] = [];
  const grouped = new Set<string>();
  for (const g of plan?.groups ?? []) {
    const members = g.filter((n) => aiIndex.has(n));
    if (members.length >= 2) {
      groups.push(members);
      for (const n of members) grouped.add(n);
    }
  }
  for (const name of aiIndex.keys()) if (!grouped.has(name)) groups.push([name]);

  groups.forEach((members, gi) => {
    if (!plan) return;
    const n = plan.columns[members[0]].choices.length;
    const hasUnique = members.some((m) => unique.has(m));
    const rng = mulberry32(deriveSeed(seed, gi));
    const order = hasUnique ? shuffledOrder(n, rng) : null;
    const idxs: number[] = [];
    for (let i = 0; i < input.count; i++) {
      idxs.push(order ? order[i % n] : Math.floor(rng() * n));
    }
    for (const m of members) {
      const ci = aiIndex.get(m) ?? 0;
      colValues[ci] = aiColumnValues(active[ci], plan.columns[m], idxs, deriveSeed(seed, 1000 + ci), unique.has(m));
    }
  });

  // それ以外はルールベースの生成 (列ごとに別シードで、他列の増減に影響されない)。
  active.forEach((spec, ci) => {
    if (colValues[ci]) return;
    const col = generateRows([spec], input.count, deriveSeed(seed, 2000 + ci));
    colValues[ci] = col.map((r) => r[0]);
  });

  const rows: CellValue[][] = [];
  for (let i = 0; i < input.count; i++) rows.push(colValues.map((c) => c[i]));
  return { columns: active.map((s) => s.column), rows };
}

/**
 * AI の計画から決定的に行を展開する。複数テーブルを渡すと親 → 子の順に生成し、
 * 親の生成値を子の FK 列へ配る (参照が壊れない)。同じ入力 + シードなら常に同じ結果。
 */
export function generateAiDataset(tables: AiTableInput[], seed: number): Record<string, AiTableRows> {
  const names = new Set(tables.map((t) => t.table));
  const done = new Set<string>();
  const ordered: AiTableInput[] = [];
  let remaining = tables.slice();
  while (remaining.length > 0) {
    const ready = remaining.filter((t) =>
      t.specs.every(
        (s) => s.strategy !== "fkRef" || !s.fkTable || s.fkTable === t.table || !names.has(s.fkTable) || done.has(s.fkTable),
      ),
    );
    // 循環参照は先頭を強制的に進める (その FK 列は NULL 生成になる)。
    const next = ready.length > 0 ? ready : [remaining[0]];
    for (const t of next) {
      ordered.push(t);
      done.add(t.table);
    }
    remaining = remaining.filter((t) => !next.includes(t));
  }
  const out: Record<string, AiTableRows> = {};
  const parentValues = new Map<string, CellValue[]>();
  ordered.forEach((input, ti) => {
    const res = expandTable(input, deriveSeed(seed, 3000 + ti), parentValues);
    out[input.table] = res;
    res.columns.forEach((c, ci) => {
      const seen = new Set<string>();
      const vals: CellValue[] = [];
      for (const r of res.rows) {
        const v = r[ci];
        if (v === null || seen.has(String(v))) continue;
        seen.add(String(v));
        vals.push(v);
      }
      parentValues.set(`${input.table}\u0000${c}`, vals);
    });
  });
  return out;
}
