// CREATE TABLE ウィザード (#460) の SQL 生成 (純ロジック)。
//
// フォームのカラム定義 (CreateTableForm) から方言に応じた CREATE TABLE 文を組み立てる。
// 識別子のクオートは sqlDialect.ts、DEFAULT のリテラルエスケープは cellEdit.ts の
// quoteString を流用する。副作用が無いので Vitest でユニットテストする。

import { quoteIdentFor } from "./sqlDialect";
import { quoteString } from "./cellEdit";

export interface ColumnDef {
  name: string;
  /** 型名 (例: VARCHAR(255), INT, TEXT)。ユーザ入力をそのまま使う。 */
  type: string;
  notNull: boolean;
  primaryKey: boolean;
  unique: boolean;
  /** 自動採番 (MySQL AUTO_INCREMENT / PostgreSQL IDENTITY / SQLite AUTOINCREMENT)。 */
  autoIncrement: boolean;
  /** DEFAULT 値。空なら付与しない。数値/キーワードは素通し、それ以外は文字列リテラル化。 */
  defaultValue: string;
}

export interface CreateTableForm {
  database?: string | null;
  table: string;
  columns: ColumnDef[];
}

/** DEFAULT 句を組み立てる。空なら null。数値・既知キーワードは素通し、他は文字列化。 */
export function formatDefault(driver: string, raw: string): string | null {
  const v = raw.trim();
  if (!v) return null;
  if (/^-?\d+(\.\d+)?$/.test(v)) return v;
  const upper = v.toUpperCase();
  const keywords = new Set([
    "NULL",
    "TRUE",
    "FALSE",
    "CURRENT_TIMESTAMP",
    "CURRENT_DATE",
    "CURRENT_TIME",
    "NOW()",
  ]);
  if (keywords.has(upper)) return upper;
  return quoteString(driver, v);
}

/** 完全修飾したテーブル名 (SQLite はスキーマ非対応なので table のみ)。 */
function qualifiedName(driver: string, database: string | null | undefined, table: string): string {
  if (driver === "sqlite" || !database) return quoteIdentFor(driver, table);
  return `${quoteIdentFor(driver, database)}.${quoteIdentFor(driver, table)}`;
}

/**
 * フォーム定義から CREATE TABLE 文を生成する。空のテーブル名/カラム名はそのまま
 * (UI 側でバリデーション)。SQLite の `INTEGER PRIMARY KEY AUTOINCREMENT` 特殊形に対応。
 */
export function buildCreateTableSql(driver: string, form: CreateTableForm): string {
  const cols = form.columns;
  const pkCols = cols.filter((c) => c.primaryKey);

  // SQLite の AUTOINCREMENT は単一 INTEGER PRIMARY KEY のときだけ有効。その場合は
  // インライン宣言にし、テーブルレベルの PRIMARY KEY 制約は付けない。
  const sqliteAutoPk =
    driver === "sqlite" &&
    pkCols.length === 1 &&
    pkCols[0].autoIncrement &&
    cols.filter((c) => c.autoIncrement).length === 1;

  const lines: string[] = cols.map((c) => columnLine(driver, c, { sqliteAutoPk }));

  // テーブルレベル PRIMARY KEY (SQLite 自動採番の特殊形を除く)。
  if (pkCols.length > 0 && !sqliteAutoPk) {
    const pkList = pkCols.map((c) => quoteIdentFor(driver, c.name)).join(", ");
    lines.push(`PRIMARY KEY (${pkList})`);
  }

  const name = qualifiedName(driver, form.database, form.table);
  return `CREATE TABLE ${name} (\n  ${lines.join(",\n  ")}\n);`;
}

function columnLine(
  driver: string,
  col: ColumnDef,
  opts: { sqliteAutoPk: boolean },
): string {
  const name = quoteIdentFor(driver, col.name);
  const parts: string[] = [name];

  // SQLite 自動採番 PK の特殊形: `INTEGER PRIMARY KEY AUTOINCREMENT`。
  if (opts.sqliteAutoPk && col.primaryKey && col.autoIncrement) {
    parts.push("INTEGER", "PRIMARY KEY", "AUTOINCREMENT");
    return parts.join(" ");
  }

  parts.push(col.type.trim() || "TEXT");

  // NOT NULL: テーブルレベル PK が NOT NULL を含意するが、明示指定も尊重する。
  if (col.notNull) parts.push("NOT NULL");
  if (col.unique && !col.primaryKey) parts.push("UNIQUE");

  if (col.autoIncrement) {
    if (driver === "mysql") parts.push("AUTO_INCREMENT");
    else if (driver === "postgres") parts.push("GENERATED BY DEFAULT AS IDENTITY");
    // SQLite の非 PK 自動採番は無効なので無視する。
  }

  const def = formatDefault(driver, col.defaultValue);
  if (def !== null) parts.push(`DEFAULT ${def}`);

  return parts.join(" ");
}
