/**
 * 行追加モーダルの「既定値 / 自動採番 / 関数値」支援 (#1357) の純ロジック。
 *
 * 1. 列メタ (`TableColumnInfo`) から「空欄なら DB が自動採番する列」「DEFAULT 式を持つ列」
 *    を判定する。判定は方言ごとの表現の違いを吸収する (MySQL は `EXTRA` の
 *    `auto_increment`、PostgreSQL は `nextval(...)` 既定値 (serial)、SQLite は単一の
 *    `INTEGER PRIMARY KEY` (rowid の別名))。
 * 2. 列の型から、DB 側で評価させる関数値 (`CURRENT_TIMESTAMP` / `NOW()` / UUID など) の
 *    チップを作る。式そのものは `sqlDialect.ts` の `insertFunctionSql` の固定カタログから
 *    だけ生まれ、利用者の入力文字列は式にならない。
 *
 * 空欄の列は INSERT から省かれる (`cellEdit.ts` の `buildInsertStatements`)。ここでは
 * それを「明示表示」するための判定だけを行い、書き込み経路には触れない。
 */

import type { TableColumnInfo } from "../api/tauri";
import { classifyEditType, type InsertFunctionValue } from "./cellEdit";
import { insertFunctionSql, type InsertFunctionId } from "./sqlDialect";

/** 空欄のときに DB がどう値を決めるかの説明。 */
export type InsertDefaultHint = { kind: "auto" } | { kind: "default"; expr: string };

/**
 * 列の既定値の出どころを判定する。自動採番が優先 (serial の既定値 `nextval(...)` も
 * 自動採番として扱う)。どちらでもなければ `null`。
 *
 * `table` は同じテーブルの全列 (SQLite の単一主キー判定に使う)。
 */
export function insertDefaultHint(
  driver: string,
  col: TableColumnInfo,
  table: TableColumnInfo[],
): InsertDefaultHint | null {
  if (isAutoGenerated(driver, col, table)) return { kind: "auto" };
  if (typeof col.default === "string") {
    return { kind: "default", expr: col.default === "" ? "''" : col.default };
  }
  return null;
}

function isAutoGenerated(driver: string, col: TableColumnInfo, table: TableColumnInfo[]): boolean {
  if (driver === "postgres") return /^nextval\(/i.test(col.default ?? "");
  if (driver === "sqlite") {
    // INTEGER PRIMARY KEY (単一主キー) は rowid の別名で、挿入時に自動採番される。
    // 複合主キーの一部や `int PRIMARY KEY` は rowid の別名ではないので対象外。
    return (
      col.key === "PRI" &&
      col.data_type.trim().toUpperCase() === "INTEGER" &&
      table.filter((c) => c.key === "PRI").length === 1
    );
  }
  // MySQL / MariaDB (未知のドライバも MySQL 扱い)。
  return /auto_increment/i.test(col.extra);
}

/**
 * 列の型で出す関数値チップ。型に合わない関数は出さず、ドライバに無い関数
 * (`insertFunctionSql` が `null`) も出さない。
 *
 * - 日時: `CURRENT_TIMESTAMP` (全ドライバ) と `NOW()` (SQLite 以外)
 * - 日付 / 時刻: `CURRENT_DATE` / `CURRENT_TIME`
 * - UUID: PostgreSQL の `uuid` 型、MySQL の `CHAR(36)` / `VARCHAR(36)` (SQLite は無し)
 */
export function insertFunctionChips(driver: string, typeName: string): InsertFunctionValue[] {
  const ids: InsertFunctionId[] = [];
  const kind = classifyEditType(typeName);
  if (kind === "datetime") ids.push("current_timestamp", "now");
  else if (kind === "date") ids.push("current_date");
  else if (kind === "time") ids.push("current_time");
  if (isUuidType(driver, typeName)) ids.push("uuid");
  const out: InsertFunctionValue[] = [];
  for (const fn of ids) {
    const sql = insertFunctionSql(driver, fn);
    if (sql !== null) out.push({ fn, sql });
  }
  return out;
}

function isUuidType(driver: string, typeName: string): boolean {
  const t = typeName.trim().toUpperCase();
  if (driver === "postgres") return t === "UUID";
  if (driver === "sqlite") return false;
  return /^(CHAR|VARCHAR)\(36\)$/.test(t);
}
