/**
 * 行追加モーダルの「既定値 / 自動採番 / 生成列 / 関数値」支援 (#1357) の純ロジック。
 *
 * 1. 列メタ (`TableColumnInfo`) から「空欄なら DB が自動採番する列」「DEFAULT 式を持つ列」
 *    「値を入れられない生成列」を判定する。判定は方言ごとの表現の違いを吸収する
 *    (MySQL は `EXTRA` の `auto_increment` / `VIRTUAL GENERATED`、PostgreSQL は `nextval(...)`
 *    既定値 (serial)、SQLite は単一の `INTEGER PRIMARY KEY` (rowid の別名))。
 * 2. 列の型から、DB 側で評価させる関数値 (`CURRENT_TIMESTAMP` / `NOW()` / UUID など) の
 *    チップを作る。チップの値は関数 ID (`fn`) だけを持ち、式は毎回 `sqlDialect.ts` の
 *    `insertFunctionSql` の固定カタログから作られる。利用者の入力文字列は式にならない。
 * 3. 行の複製の種から、自動採番・生成列の値を外す (DB が決める列に古い値を入れて
 *    重複キーや生成列エラーで失敗しないため)。
 *
 * 空欄の列は INSERT から省かれる (`cellEdit.ts` の `buildInsertStatements`)。ここでは
 * それを「明示表示」するための判定だけを行い、書き込み経路には触れない。
 */

import type { Column, TableColumnInfo } from "../api/tauri";
import { classifyEditType, type InsertFunctionValue, type PendingInsertRow } from "./cellEdit";
import { insertFunctionSql, type InsertFunctionId } from "./sqlDialect";

/** 空欄のときに DB がどう値を決めるか、または入力できないことの説明。 */
export type InsertDefaultHint =
  | { kind: "auto" }
  | { kind: "default"; expr: string }
  | { kind: "generated" };

/**
 * 列の既定値の出どころを判定する。生成列が最優先 (値を入れるとエラーになる)、次に自動採番
 * (serial の既定値 `nextval(...)` も自動採番として扱う)。どれでもなければ `null`。
 *
 * `table` は同じテーブルの全列 (SQLite の単一主キー判定に使う)。
 */
export function insertDefaultHint(
  driver: string,
  col: TableColumnInfo,
  table: TableColumnInfo[],
): InsertDefaultHint | null {
  if (isGenerated(col)) return { kind: "generated" };
  if (isAutoGenerated(driver, col, table)) return { kind: "auto" };
  if (typeof col.default === "string") {
    return { kind: "default", expr: col.default === "" ? "''" : col.default };
  }
  return null;
}

/**
 * 生成列 (値を入れるとエラーになる列)。MySQL / MariaDB は `EXTRA` に
 * `VIRTUAL GENERATED` / `STORED GENERATED` (MariaDB は `PERSISTENT GENERATED`) が出る。
 * PostgreSQL の `is_generated` は現在のバックエンドが取得していないため判定できない。
 */
function isGenerated(col: TableColumnInfo): boolean {
  return /\bGENERATED\b/i.test(col.extra);
}

function isAutoGenerated(driver: string, col: TableColumnInfo, table: TableColumnInfo[]): boolean {
  if (driver === "postgres") return /^nextval\(/i.test(col.default ?? "");
  if (driver === "sqlite") {
    // INTEGER PRIMARY KEY (単一主キー) は rowid の別名で、挿入時に自動採番される。
    // 複合主キーの一部や `int PRIMARY KEY` は rowid の別名ではないので対象外。
    // 制約: `WITHOUT ROWID` テーブルでは単一の INTEGER 主キーでも rowid の別名にならず、
    // 自動採番ではない。PRAGMA table_info はテーブルの WITHOUT ROWID 指定を返さないため、
    // ここでは検出できず、その場合は自動採番と表示する (値を入れれば従来どおり INSERT される)。
    return (
      col.key === "PRI" &&
      col.data_type.trim().toUpperCase() === "INTEGER" &&
      table.filter((c) => c.key === "PRI").length === 1
    );
  }
  // MySQL / MariaDB (未知のドライバも MySQL 扱い)。
  return /auto_increment/i.test(col.extra);
}

/**
 * 列の型で出す関数値チップ。型に合わない関数は出さず、ドライバに無い関数
 * (`insertFunctionSql` が `null`) も出さない。
 *
 * 型名は `metaType` (`TableColumnInfo.data_type`、方言の正しい型名) を優先し、無ければ
 * `typeName` (結果列の型名。MySQL では `CHAR` のように長さが落ちる) を使う。
 *
 * - 日時: `CURRENT_TIMESTAMP` (全ドライバ) と `NOW()` (SQLite 以外)
 * - 日付: `CURRENT_DATE`
 * - 時刻: `CURRENT_TIME` (PostgreSQL の `timetz` を含む)
 * - UUID: PostgreSQL の `uuid` 型 (`gen_random_uuid()`、PostgreSQL 13 以降)、MySQL の
 *   `CHAR(36)` / `VARCHAR(36)` (`UUID()`)。SQLite は無し
 */
export function insertFunctionChips(
  driver: string,
  typeName: string,
  metaType?: string | null,
): InsertFunctionValue[] {
  const declared = metaType && metaType.trim() !== "" ? metaType : typeName;
  const ids: InsertFunctionId[] = [];
  const kind = classifyEditType(declared);
  if (kind === "datetime") ids.push("current_timestamp", "now");
  else if (kind === "date") ids.push("current_date");
  else if (kind === "time" || isTimeWithZone(declared)) ids.push("current_time");
  if (isUuidType(driver, declared)) ids.push("uuid");
  const out: InsertFunctionValue[] = [];
  for (const fn of ids) {
    if (insertFunctionSql(driver, fn) !== null) out.push({ fn });
  }
  return out;
}

/**
 * `classifyEditType` は `time` を素の TIME だけ返し、`TIMETZ` (PostgreSQL) や
 * `TIME WITH TIME ZONE` は `other` になる。型別エディタ (#1355) への影響を避けるため、
 * 時刻チップの判定だけここで補う。
 */
function isTimeWithZone(typeName: string): boolean {
  const base = typeName.trim().toUpperCase().replace(/\(.*$/, "").trim();
  return base === "TIMETZ" || base === "TIME WITH TIME ZONE" || base === "TIME WITHOUT TIME ZONE";
}

function isUuidType(driver: string, typeName: string): boolean {
  const t = typeName.trim().toUpperCase();
  if (driver === "postgres") return t === "UUID";
  if (driver === "sqlite") return false;
  // MariaDB 10.7 以降の uuid 型 (MySQL にはネイティブ型が無い)。
  if (t === "UUID") return true;
  return /^(CHAR|VARCHAR)\(36\)$/.test(t);
}

/**
 * 行の複製 (#820) の種から、DB が決める列 (自動採番・生成列) の値を外す。種は結果グリッドの
 * 元の行の値なので、自動採番列に残すと重複キーで失敗し、生成列に残すとエラーになる。
 * 列メタが無い (`tableColumns` が空) 場合は何もしない。
 */
export function stripNonInsertableSeed(
  driver: string,
  seed: PendingInsertRow,
  columns: Column[],
  tableColumns: TableColumnInfo[],
): PendingInsertRow {
  const out: PendingInsertRow = { ...seed };
  columns.forEach((c, i) => {
    const meta = tableColumns.find((m) => m.name === c.name);
    if (!meta) return;
    const hint = insertDefaultHint(driver, meta, tableColumns);
    if (hint?.kind === "auto" || hint?.kind === "generated") delete out[i];
  });
  return out;
}
