import type { DriverKind, SyncPlan, SyncStatement } from "../api/tauri";

/**
 * スキーマ比較の `SyncPlan` (`SchemaCompareView` が `api.generateSyncSql` から
 * 得た反映 SQL) を Flyway / golang-migrate / sqlx / 汎用形式の up/down
 * マイグレーションファイルとして書き出すための純粋ロジック (#744)。
 *
 * ファイル書き込みや保存ダイアログといった副作用は持たない
 * (`MigrationExportModal.tsx` 側の責務)。`up` は `SchemaCompareView` が既に
 * 持つ `SyncPlan` をそのまま SQL 化するだけで新規ロジックはない。`down` は
 * ソース/ターゲットを入れ替えて `compare_schema` → `generate_sync_sql` を
 * 再実行して得た**別の** `SyncPlan` を同じ関数でファイル化する — つまりここに
 * ある関数はどちら向きの `SyncPlan` にも対称に使える。
 */

/** 対応するマイグレーションツールのファイル名規則。 */
export type MigrationFormat = "flyway" | "golang-migrate" | "sqlx" | "generic";

/** UI のフォーマット選択肢 (表示順)。 */
export const MIGRATION_FORMATS: readonly MigrationFormat[] = [
  "flyway",
  "golang-migrate",
  "sqlx",
  "generic",
];

/**
 * 名前を英数字と `_` のみへサニタイズする。それ以外の文字 (空白・記号・非 ASCII
 * など) は `_` に置き換え、連続する `_` は 1 つに畳み、前後の `_` は取り除く。
 * サニタイズ後に空文字列になった場合 (例: 全角文字のみの入力) は `migration`
 * にフォールバックする。
 */
export function sanitizeMigrationName(input: string): string {
  const replaced = input.replace(/[^A-Za-z0-9_]+/g, "_");
  const collapsed = replaced.replace(/_+/g, "_").replace(/^_+|_+$/g, "");
  return collapsed || "migration";
}

/**
 * ソース/ターゲットの DB 名から既定のマイグレーション名を組み立てる
 * (サニタイズ済み)。両者が同じ、または一方が空ならその DB 名のみを使い、
 * 両方空なら `schema_sync` にフォールバックする。
 */
export function defaultMigrationName(sourceDatabase: string, targetDatabase: string): string {
  if (sourceDatabase && targetDatabase && sourceDatabase !== targetDatabase) {
    return sanitizeMigrationName(`${sourceDatabase}_to_${targetDatabase}`);
  }
  return sanitizeMigrationName(sourceDatabase || targetDatabase || "schema_sync");
}

/**
 * `yyyyMMddHHmmss` 形式のタイムスタンプ版番号 (UTC 固定)。ホストのタイムゾーン
 * に依存せず決定的にするため UTC の各コンポーネントを使う (テスト容易性のため
 * `Date` は呼び出し側から渡す — このモジュール自身は `Date.now()` を呼ばない)。
 */
export function migrationVersion(date: Date): string {
  const pad = (n: number) => String(n).padStart(2, "0");
  return (
    String(date.getUTCFullYear()) +
    pad(date.getUTCMonth() + 1) +
    pad(date.getUTCDate()) +
    pad(date.getUTCHours()) +
    pad(date.getUTCMinutes()) +
    pad(date.getUTCSeconds())
  );
}

/** 1 マイグレーション分の up/down ファイル名。 */
export interface MigrationFileNames {
  up: string;
  down: string;
}

/**
 * フォーマットごとのファイル名規則。`name` はあらかじめ
 * {@link sanitizeMigrationName} 済みであることを前提とする。
 *
 * - Flyway: `V<version>__<name>.sql` / `U<version>__<name>.sql`
 * - golang-migrate: `<version>_<name>.up.sql` / `<version>_<name>.down.sql`
 * - sqlx (`-r` reversible 形式): `<version>_<name>.up.sql` / `.down.sql`
 *   (golang-migrate と同じ命名だが、ツール選択の意図を明示するため別の
 *   フォーマット値として扱う)
 * - 汎用: `<name>.up.sql` / `<name>.down.sql` (バージョン番号を含めない)
 */
export function migrationFileNames(
  format: MigrationFormat,
  version: string,
  name: string,
): MigrationFileNames {
  switch (format) {
    case "flyway":
      return { up: `V${version}__${name}.sql`, down: `U${version}__${name}.sql` };
    case "golang-migrate":
      return { up: `${version}_${name}.up.sql`, down: `${version}_${name}.down.sql` };
    case "sqlx":
      return { up: `${version}_${name}.up.sql`, down: `${version}_${name}.down.sql` };
    case "generic":
      return { up: `${name}.up.sql`, down: `${name}.down.sql` };
  }
}

/** ヘッダコメントに載せる接続端点のメタ情報。秘密情報 (パスワード等) は含まない
 *  — `profiles.json` に保存される非秘密フィールドのみを反映する。 */
export interface MigrationEndpointMeta {
  profileName: string;
  driver: DriverKind;
  database: string;
  /** TCP 系ドライバのホスト。SQLite では null。 */
  host: string | null;
  port: number | null;
  /** SQLite のファイルパス。TCP 系ドライバでは null。 */
  filePath: string | null;
}

function describeEndpoint(meta: MigrationEndpointMeta): string {
  const location =
    meta.driver === "sqlite"
      ? (meta.filePath ?? "(no file path)")
      : `${meta.host ?? "?"}:${meta.port ?? "?"}`;
  return `${meta.profileName} [${meta.driver}] ${location} / database=${meta.database}`;
}

export interface MigrationHeaderOptions {
  generatedAt: Date;
  format: MigrationFormat;
  direction: "up" | "down";
  source: MigrationEndpointMeta;
  target: MigrationEndpointMeta;
}

/**
 * ファイル冒頭のヘッダコメント: 生成日時・フォーマット・向き (up/down)・
 * 比較元/先の非秘密エンドポイント情報・「noobDB により生成」の注記。
 */
export function buildMigrationHeader(opts: MigrationHeaderOptions): string {
  return [
    "-- Generated by noobDB (schema comparison)",
    `-- Generated at: ${opts.generatedAt.toISOString()}`,
    `-- Direction: ${opts.direction}`,
    `-- Format: ${opts.format}`,
    `-- Source: ${describeEndpoint(opts.source)}`,
    `-- Target: ${describeEndpoint(opts.target)}`,
  ].join("\n");
}

/** `SyncStatement` 列をセミコロン区切りの SQL 本文にする。空なら注記コメントを
 *  返す (例: down 側で反映すべき差分が無いとき)。 */
export function renderMigrationStatements(statements: SyncStatement[]): string {
  if (statements.length === 0) {
    return "-- (no statements)";
  }
  return statements.map((s) => `${s.sql};`).join("\n\n");
}

/**
 * `SyncPlan.warnings` を SQL コメントブロックにする。SQLite の in-place 変更
 * 不可など、down 側で反映できない差分はここに現れるので、コメントとしてファイルへ
 * そのまま明示する (#744)。警告が無ければ空文字列を返す。
 */
export function renderMigrationWarnings(warnings: string[]): string {
  if (warnings.length === 0) return "";
  const body = warnings
    .map((w) =>
      w
        .split("\n")
        .map((line) => `--   ${line}`)
        .join("\n"),
    )
    .join("\n");
  return ["-- Warnings (could not be expressed as SQL — review manually):", body].join("\n");
}

/** ヘッダ + SQL 本文 + 警告コメントを 1 ファイル分のテキストへ組み立てる。 */
export function buildMigrationFile(header: string, plan: SyncPlan): string {
  const parts = [header, renderMigrationStatements(plan.statements)];
  const warnings = renderMigrationWarnings(plan.warnings);
  if (warnings) parts.push(warnings);
  return `${parts.join("\n\n")}\n`;
}
